#!/usr/bin/env bash

dir="~/deploy/app"
app="router-logs"
deploy_dir="$dir/$app"
crondir=/etc/cron.d

GIT_WORK_TREE="$deploy_dir" git checkout -f

cd "$deploy_dir"

## build steps here ##
sudo cp lib/crontab "$cron/$app"

echo "all done"

exit 0
