#!/usr/bin/env bash

get_log(){
  device=$1
  log_dir="./logs"
  log="$log_dir/$device"
  user="root"
  command="cat /var/log/messages"

  ssh "$user@$device" "$command" > "$log"

  process $device $log
}

process(){
  device=$1
  log=$2
  processed="$log_dir/processed"
  year=$(date +%Y)

  awk -F' ' '{ \
    printf "%s %s %s,%s,", $1,$2,2016,$3; \
    printf "%s,%s,%s,", $4,$5,$6; \
    printf "\"";for(i=7;i<=NF;i++)printf "%s ",$i; print"\""}' \
    "$log"  > "$processed"

  load "$device" "$processed"
}

load() {
  device=$1
  processed=$2
  staging="./sql/staging.sql"

  psql -h odroid -d router-logs -c "truncate table log_staging;"

  psql -h odroid -d router-logs -c "\copy log_staging(date,time,device,syslog_tag,program,log) from '$processed' delimiter ',' csv;"

  psql -h odroid -d router-logs -f $staging
}


