#!/usr/bin/env bash
set -eou pipefail

get_log(){
  device=$1
  log_dir="./logs"
  log="$log_dir/$device"
  user="root"
  command="cat /var/log/messages"

  ssh "$user@$device" "$command" > "$log"

  process $device $log
}

get_clog(){
  device=$1
  log_dir="./logs"
  log="$log_dir/$device"
  user="root"
  command="clog /var/log/system.log"

  ssh "$user@$device" "$command" > "$log"

  process $device $log
}

process(){
  device=$1
  log=$2
  processed="$log_dir/processed"
  year=$(date +%Y)

  case "$device" in
    (pfsense | pfsense.)
      cat "$log" | \
      sed 's/,//g' | \
      sed 's/://g' | \
      sed 's/;//g' | \
      sed 's|["'\'']||g' | \
      awk -v year="$year" -F' ' '{ \
        printf "%s %s %s,%s,", $1,$2,year,$3; \
        printf "%s,%s,%s,", $4,"system.log",$5; \
        printf "\"";for(i=6;i<=NF && i<=15;i++)printf "%s ",substr($i,0,12); print"\""}' \
        > "$processed" ;;
    (router | router. | firewall | firewall. | *)
      cat "$log" | \
      sed 's/,//g' | \
      sed 's/://g' | \
      sed 's/;//g' | \
      sed 's|["'\'']||g' | \
      awk -v year="$year" -F' ' '{ \
        printf "%s %s %s,%s,", $1,$2,year,$3; \
        printf "%s,%s,%s,", $4,$5,$6; \
        printf "\"";for(i=7;i<=NF && i<=15;i++)printf "%s ",substr($i,0,12); print"\""}' \
        > "$processed" ;;
    esac

  load "$device" "$processed"
}

load() {
  device=$1
  processed=$2
  staging="./sql/staging.sql"
  host="odroid"
  host="rspi2"          # Pi acting as server since odroid down

  psql -h "$host" -d router-logs -c "truncate table log_staging;"

  psql -h "$host" -d router-logs -c "\copy log_staging(date,time,device,syslog_tag,program,log) from '$processed' delimiter ',' csv;"

  psql -h "$host" -d router-logs -f $staging
}
