#!/usr/bin/env bash

firewall="firewall."
router="router."

source ./src/etl

# For PF Sense
#get_log_bsd $firewall

# For Tomato-shibby
get_log $firewall

# Router is always Tomato-shibby
get_log $router
