#!/usr/bin/env bash

firewall="firewall."
router="router."
user="root"
log_dir="./../logs"
command="cat /var/log/messages"

get_log(){
  device=$1
  log="$log_dir/$device"

  ssh "$user@$device" "$command" > "$log"

  process $device $log
}

process(){
  device=$1
  log=$2
  processed="$log_dir/processed"

  awk -F' ' '{printf "%s %s %s,%s,", $1,$2,2016,$3; printf "%s,%s,%s,", $4,$5,$6;for(i=7;i<=NF;i++)printf "%s ",$i; print""}' "$log"  > "$processed"

  load "$device" "$processed"
}

load() {
  device=$1
  processed=$2

  psql -h odroid -d router-logs -c "\copy log from '$processed' delimiter ',' csv;"
}

get_log $firewall
#get_log $router
